version: 2.1

commands:
  setup-pip-cache:
    steps:
      - restore_cache:
          name: Restoring pip cache
          key: &pipcachekey pipcache-v1-pyv3-8-9-{{ checksum "Pipfile.lock" }}
      - run:
          command: pipenv sync
      - save_cache:
          key: *pipcachekey
          paths:
            - ".venv"

  install-serverless-framework:
    steps:
      - run:
          name: Install Serverless Framework
          command: yarn add serverless
      - run:
          name: Validate Install
          command: yarn run which sls
      - run:
          name: Check version
          command: yarn run sls --version

jobs:
  main:
    docker: 
      - image: cimg/node:lts
    steps:
      - install-serverless-framework

workflows:
  main:
    jobs:
      - main
